#!/bin/bash

source bin/stack_functions

preamble_setup

export CONTROLLER_NAME=127.0.0.1

controllers=`sudo ovs-vsctl get-controller t1sw1`

local=
if [ "$1" == local ]; then
    local=y
    shift
fi

bridges=$(sudo ovs-vsctl show | fgrep Bridge | wc -l)
if [ $bridges != 6 ]; then
    echo System misconfiguration: found $bridges bridges, expected 6.
    exit 2
fi

containers=$(docker ps  | fgrep forch- | wc -l)
if [ $containers != 7 ]; then
    echo System misconfiguration: found $containers containers, expected 7.
    exit 2
fi

cap_base=10
ping_count=10
num_pairs=12
cap_length=$((cap_base + ping_count + num_pairs * 2))

faucet_log=inst/forch-faucet-1/faucet.log
forch_log=inst/forch-faucet-1/forch.log

#################################################################################

echo Capturing $faucet_log...
rm -f $faucet_log
tail --retry -f $faucet_log &

reset_system

reset_stack

# Test that the 'local' mode of faucet is working properly.
echo 'print("supercalifragilisticexpialidocious")' > faucet/faucet/python_test.py
docker exec forch-faucet-1 python -m faucet.python_test 2>&1 | tee -a $TEST_RESULTS
rm faucet/faucet/python_test.py

curl -s http://localhost:8001 > $OUT_DIR/faucet_varz.txt
fgrep 'port_lacp_state{' $OUT_DIR/faucet_varz.txt | sort | tee -a $TEST_RESULTS

restart_forch

# Basic one-time test of web-server and config
curl http://$CONTROLLER_NAME:9019/index.html > $OUT_DIR/index.html
fgrep "Network Operations Administrative Helper" $OUT_DIR/index.html || exit 1
curl http://$CONTROLLER_NAME:9019/protos.html > $OUT_DIR/protos.html
fgrep "forch/proto/system_state.proto" $OUT_DIR/protos.html || exit 1
curl http://$CONTROLLER_NAME:9019/sys_config > $OUT_DIR/sys_config.json
jq '.faucet.behavioral.dps."nz-kiwi-t2sw3"'.faucet_dp_mac $OUT_DIR/sys_config.json | tee -a $TEST_RESULTS
jq '.faucet.warnings.faucet_dp_mac' $OUT_DIR/sys_config.json | tee -a $TEST_RESULTS
jq '.ryu.echo_request_interval' $OUT_DIR/sys_config.json | tee -a $TEST_RESULTS
test_varz_value faucet_config_warning_count 8302 forch

echo %%% initial solid state | tee -a $TEST_RESULTS
test_stack -solid
test_forch -solid

echo %%% orphaned t1sw1 | tee -a $TEST_RESULTS
reset_stack
sudo ip link set t1sw1-eth6 down
sudo ip link set t1sw1-eth9 down
sudo ip link set t1sw1-eth10 down
sudo ip link set t1sw1-eth11 down
test_stack -orphaned
test_forch -orphaned

exit 0

echo %%% reset stack | tee -a $TEST_RESULTS
restart_ovs
reset_stack
test_forch -reset

echo %%% restarting Forch | tee -a $TEST_RESULTS
restart_forch
sleep 32
test_forch -restart

echo Killing forch...
sudo kill `ps ax | fgrep forch | awk '{print $1}'`

echo Killing tails...
kill `ps ax | fgrep $faucet_log | fgrep -v fgrep | awk '{print $1}'`
kill `ps ax | fgrep $forch_log | fgrep -v fgrep | awk '{print $1}'`

echo Done with test_stack.
